'use client'

import { motion } from 'framer-motion'
import { useEffect, useState } from 'react'
import VideoModal from './VideoModal'

export default function ExamplePDF() {
  const [mounted, setMounted] = useState(false)
  const [isVideoModalOpen, setIsVideoModalOpen] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <section className="py-24 bg-gradient-to-b from-white to-gray-50/50 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0 opacity-[0.02] bg-[radial-gradient(circle_at_1px_1px,rgb(0,0,0)_1px,transparent_0)] [background-size:24px_24px]" />
      
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <motion.div
          initial={mounted ? { opacity: 0, y: 20 } : { opacity: 1, y: 0 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            See it in Action
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Download an example SWPPP generated by Storm to see the quality yourself.
          </p>
        </motion.div>

        <motion.div
          initial={mounted ? { opacity: 0, y: 30 } : { opacity: 1, y: 0 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="relative"
        >
          {/* Card Container */}
          <div className="relative rounded-3xl overflow-hidden bg-gradient-to-br from-white to-gray-50/80 backdrop-blur-xl border border-gray-200/60 shadow-2xl">
            {/* Gradient overlay */}
            <div className="absolute inset-0 bg-gradient-to-br from-storm-primary/5 via-transparent to-storm-secondary/5" />
            
            {/* Content */}
            <div className="relative p-8 md:p-12">
              <div className="flex flex-col md:flex-row items-center gap-8">
                {/* PDF Icon */}
                <div className="flex-shrink-0">
                  <div className="relative">
                    <div className="absolute -inset-4 bg-gradient-to-br from-storm-primary/20 to-storm-secondary/20 rounded-2xl blur-xl" />
                    <div className="relative w-24 h-24 md:w-32 md:h-32 rounded-2xl bg-gradient-to-br from-storm-primary to-storm-secondary p-6 md:p-8 shadow-xl">
                      <svg 
                        className="w-full h-full text-white" 
                        fill="none" 
                        viewBox="0 0 24 24" 
                        stroke="currentColor"
                      >
                        <path 
                          strokeLinecap="round" 
                          strokeLinejoin="round" 
                          strokeWidth={2} 
                          d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" 
                        />
                      </svg>
                    </div>
                  </div>
                </div>

                {/* Text and Button */}
                <div className="flex-1 text-center md:text-left">
                  <h3 className="text-2xl md:text-3xl font-bold mb-3 text-gray-900">
                    Storm Business Park - Traditional Risk 2
                  </h3>
                  <p className="text-gray-600 mb-6 leading-relaxed">
                    We prepared a SWPPP for a fictional project in the Los Angeles Region 4 area called &quot;Storm Business Park.&quot;
                    The project is a new commercial development on a property that was previously an auto wrecking yard. The receiving water has TMDL impairments.
                  </p>
                  <div className="flex flex-col sm:flex-row gap-4">
                    <motion.a
                      href="/Storm Business Park-69236f7caac38601adc9e053.pdf"
                      download
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      className="inline-flex items-center justify-center gap-3 px-8 py-4 bg-gradient-storm text-white rounded-full font-semibold text-lg shadow-lg hover:shadow-xl transition-shadow"
                    >
                      <svg 
                        className="w-5 h-5" 
                        fill="none" 
                        viewBox="0 0 24 24" 
                        stroke="currentColor"
                      >
                        <path 
                          strokeLinecap="round" 
                          strokeLinejoin="round" 
                          strokeWidth={2} 
                          d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" 
                        />
                      </svg>
                      Download Example PDF
                    </motion.a>
                    <motion.button
                      onClick={() => setIsVideoModalOpen(true)}
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      className="px-8 py-4 bg-white text-storm-primary rounded-full font-semibold text-lg border-2 border-storm-primary hover:bg-storm-light transition-colors"
                    >
                      Watch Demo
                    </motion.button>
                  </div>
                </div>
              </div>
            </div>

            {/* Decorative elements */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-storm-primary/10 to-transparent rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />
            <div className="absolute bottom-0 left-0 w-48 h-48 bg-gradient-to-tr from-storm-secondary/10 to-transparent rounded-full blur-2xl translate-y-1/2 -translate-x-1/2" />
          </div>
        </motion.div>
      </div>

      {/* Video Modal */}
      <VideoModal
        isOpen={isVideoModalOpen}
        onClose={() => setIsVideoModalOpen(false)}
        videoUrl="https://player.vimeo.com/video/1139431440?h=5aba4e318d"
      />
    </section>
  )
}

